### ISSUE TITLE
Thanks for the inspiration

### ISSUE THREAD

**Issue by moises-silva** [areski/freeswitch-telegraf-plugin#1]
I found this repo when googling telegraf and freeswitch. I started using your script,  but eventually came up with a different implementation: https://github.com/moises-silva/freeswitch-telegraf

Feedback welcomed, and I just wanted to open this issue to let you know about it and see if in the future we can collaborate to enhance and/or merge the projects.

**Comment by areski** [comment]
Very nice implementation, I love it! Nice to discover greenswitch as well.

Let me share some original thoughts on the project.
`freeswitch-telegraf-plugin` was a quick hack to fulfill the basic need, I was planning to enhance it to an async app, ideally using python-asyncio or Elixir (https://github.com/areski/freeswitch_realtime) and so not using telegraf, my ideal goals would be to catch some custom events from FreeSWITCH to push them to InfluxDB along with the actual metrics collected from the Freeswitch API.

Here you can see this application doing something similar using Twisted: https://github.com/wimactel/FreeSwitch-DataDog-Metrics

I think we all want a neat way to save some metrics (also app related) to a timeseries DB (InfluxDB or other)

**Comment by moises-silva** [comment]
@areski thanks for sharing, sounds like a nice idea. If you end up implementing it, let me know!
